### ISSUE TITLE
Version 0.25.1 cannot Connect to Resolve API

### ISSUE THREAD

**Issue by iamfibi** [octimot/StoryToolkitAI#207]
**Describe the bug**
In previous version, The tool work completely fine with the Resolve API. But in recent updates, many errors says "conflicted" (unfortunately, i forgot to screenshot this). Then I uninstalled all the tools including the python and the tools itself then reinstalled. but after reinstalled, the API resolve cannot connect and showing this

![Image](https://github.com/user-attachments/assets/f16e903b-423e-45d9-822b-d7112f7d5033)

Btw I'm using git version

 - OS: Windows 11
 - Python versions installed on machine: 3.11.9
 - StoryToolkitAI Version 0.25.1

**Comment by octimot** [comment]
Does the tool start at all? Can you please include your app.log in this report?

**Comment by iamfibi** [comment]
Thanks to the response. Yes the tool work fine. It's only just cannot connect to Resolve API (I have Resolve Studio)

here is the app.log
Platform: Windows 10
 Platform version: 10.0.26100
 OS: 10 10.0.26100 SP0 Multiprocessor Free  ('', '', '')  
 running Python 3.11.9.final.0
-------------- (__main__.py:32)
2025-02-19 15:35:06,544 - StAI - DEBUG: Checking package requirements from C:\Users\DESIGN 2\Desktop\Untuk Transcription\StoryToolkitAI\requirements.txt (__main__.py:66)
2025-02-19 15:35:06,917 - StAI - DEBUG: FFmpeg not found in current working directory: C:\Users\DESIGN 2\Desktop\Untuk Transcription\StoryToolkitAI\ffmpeg.exe. (storytoolkitai.py:596)
2025-02-19 15:35:06,918 - StAI - DEBUG: FFmpeg not found in _internal directory: C:\Users\DESIGN 2\Desktop\Untuk Transcription\StoryToolkitAI\_internal\ffmpeg.exe (storytoolkitai.py:606)
2025-02-19 15:35:06,918 - StAI - DEBUG: FFMPEG_BINARY env variable is empty. Looking for FFmpeg in PATH. (storytoolkitai.py:615)
2025-02-19 15:35:06,919 - StAI - DEBUG: Checking ffmpeg binary: C:\ProgramData\chocolatey\bin\ffmpeg.EXE (storytoolkitai.py:626)
2025-02-19 15:35:06,959 - StAI - DEBUG: FFmpeg exit code: 1 (storytoolkitai.py:631)
2025-02-19 15:35:06,959 - StAI - DEBUG: FFmpeg found at C:\ProgramData\chocolatey\bin\ffmpeg.EXE (storytoolkitai.py:634)
2025-02-19 15:35:13,481 - StAI - DEBUG: Loading config file C:\Users\DESIGN 2\StoryToolkitAI\config.json. (storytoolkitai.py:365)
2025-02-19 15:35:13,481 - StAI - DEBUG: No API key found. (storytoolkitai.py:442)
2025-02-19 15:35:13,481 - StAI - DEBUG: Checking for latest version on api.storytoolkit.ai. (storytoolkitai.py:478)
2025-02-19 15:35:13,504 - StAI - INFO: [1m[4mRunning StoryToolkitAI version 0.25.1  (storytoolkitai.py:91)
2025-02-19 15:35:13,505 - StAI - DEBUG: Using cpu for Torch. (toolkit_ops.py:761)
2025-02-19 15:35:13,505 - StAI - DEBUG: Resolve API disabled via config. (toolkit_ops.py:204)
2025-02-19 15:35:13,505 - StAI - DEBUG: No items left in the queue. Try to ping the queue again later. (processing_queue.py:833)
2025-02-19 15:35:13,584 - StAI - DEBUG: Running with TK 8.6.12 (toolkit_ui.py:1405)
2025-02-19 15:35:13,633 - StAI - DEBUG: Loading project from C:\Users\DESIGN 2\StoryToolkitAI\projects\EPS. 2 - KAZAKHSTAN (projects.py:273)
2025-02-19 15:35:13,633 - StAI - DEBUG: Loading project from C:\Users\DESIGN 2\StoryToolkitAI\projects\PAGAR LAU VS GAS MELON (projects.py:273)
2025-02-19 15:35:13,634 - StAI - DEBUG: Loading project from C:\Users\DESIGN 2\StoryToolkitAI\projects\Untitled Project (projects.py:273)
2025-02-19 15:35:14,173 - StAI - INFO: Starting StoryToolkitAI GUI (toolkit_ui.py:3148)
2025-02-19 15:35:14,586 - StAI - DEBUG: No update available. (toolkit_ui.py:1600)
2025-02-19 15:35:15,514 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:15,515 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:15,515 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:15,515 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:15,516 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:15,516 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:15,516 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:15,516 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:15,517 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:15,517 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:15,517 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:15,517 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:16,256 - StAI - DEBUG: MotsResolve module initialized. (mots_resolve.py:42)
2025-02-19 15:35:17,915 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:17,915 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:17,916 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:17,916 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:17,916 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:17,916 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:17,916 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:17,917 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:17,917 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:17,917 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-19 15:35:17,917 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2281)
2025-02-19 15:35:17,918 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)

**Comment by octimot** [comment]
2025-02-19 15:35:13,505 - StAI - DEBUG: Resolve API disabled via config. (toolkit_ops.py:204)

It looks like you disabled Resolve API from the tool preferences (or maybe you confirmed to keep it disabled when it stopped working).

**Comment by iamfibi** [comment]
I can't remember I disabled the Resolve API though. after I run the tool again and enable Resolve API, the tool cannot start at all

here's the new changelog
Platform: Windows 10
 Platform version: 10.0.26100
 OS: 10 10.0.26100 SP0 Multiprocessor Free  ('', '', '')  
 running Python 3.11.9.final.0
-------------- (__main__.py:32)
2025-02-19 15:54:04,068 - StAI - DEBUG: Checking package requirements from C:\Users\DESIGN 2\Desktop\Untuk Transcription\StoryToolkitAI\requirements.txt (__main__.py:66)
2025-02-19 15:54:04,855 - StAI - DEBUG: FFmpeg not found in current working directory: C:\Users\DESIGN 2\Desktop\Untuk Transcription\StoryToolkitAI\ffmpeg.exe. (storytoolkitai.py:596)
2025-02-19 15:54:04,857 - StAI - DEBUG: FFmpeg not found in _internal directory: C:\Users\DESIGN 2\Desktop\Untuk Transcription\StoryToolkitAI\_internal\ffmpeg.exe (storytoolkitai.py:606)
2025-02-19 15:54:04,857 - StAI - DEBUG: FFMPEG_BINARY env variable is empty. Looking for FFmpeg in PATH. (storytoolkitai.py:615)
2025-02-19 15:54:04,857 - StAI - DEBUG: Checking ffmpeg binary: C:\ProgramData\chocolatey\bin\ffmpeg.EXE (storytoolkitai.py:626)
2025-02-19 15:54:04,934 - StAI - DEBUG: FFmpeg exit code: 1 (storytoolkitai.py:631)
2025-02-19 15:54:04,934 - StAI - DEBUG: FFmpeg found at C:\ProgramData\chocolatey\bin\ffmpeg.EXE (storytoolkitai.py:634)
2025-02-19 15:54:24,414 - StAI - DEBUG: Loading config file C:\Users\DESIGN 2\StoryToolkitAI\config.json. (storytoolkitai.py:365)
2025-02-19 15:54:24,420 - StAI - DEBUG: No API key found. (storytoolkitai.py:442)
2025-02-19 15:54:24,420 - StAI - DEBUG: Checking for latest version on api.storytoolkit.ai. (storytoolkitai.py:478)
2025-02-19 15:54:24,445 - StAI - INFO: [1m[4mRunning StoryToolkitAI version 0.25.1  (storytoolkitai.py:91)
2025-02-19 15:54:24,445 - StAI - DEBUG: Using cpu for Torch. (toolkit_ops.py:761)
2025-02-19 15:54:24,445 - StAI - DEBUG: MotsResolve module initialized. (mots_resolve.py:42)

**Comment by octimot** [comment]
Unfortunately, we cannot reproduce this issue on our systems, so it's very difficult to tell what the problem is without a proper debug.

Most likely you have some versions of Python installed on your system that are in conflict with each other.

Please refer to this section about [the Davinci Resolve Studio integration](https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#davinci-resolve-studio-integrations)

**Comment by iamfibi** [comment]
Hey, just want to update. I already uninstalled the python version, and installed the new one. the problem still persist. I also reinstalled my windows (I know it's a bit excessive) to ensure my python version didn't conflict (of course it's a clean install). The problem is still there but the tool work perfectly fine. I don't know how exactly the problem only happened to me but this problem only occurred when I updated to version 0.25. 

Even though I can't connect to resolve api, otherwise the tool still work perfectly fine. Thanks for your hardwork to make this tool!

**Comment by octimot** [comment]
I agree! Re-installing is really excessive, but it's also weird that this didn't solve it!

Could you open DaVinci Resolve, then go to Console, select py3 and type in the following:
```
import sys
print(sys.version)
```
What version does it return there?

Also, did you install python 3.11 in Program Files (for all users), or just for your user? You can figure out where python is installed by opening a command prompt and typing `where python` or `where py`. BTW, if you're still there, could you type in `py -0` and check which version does the installer report back?

Cheers!

**Comment by iamfibi** [comment]
Just checking the Davinci resolve console, it appears as the image shown below

![Image](https://github.com/user-attachments/assets/d78fbaa5-cbb2-452f-9338-317d991a8180)

For the python 3.11 I installed on all users like the image shown below

![Image](https://github.com/user-attachments/assets/c86c107a-ff3d-45fa-9bc1-ca122f3042b3)

**Comment by sonderling** [comment]
Hi after closed topic FileNotFoundError: [Errno 2] transcription_template_example.yaml the program works.
But.....

 the same error appeared with Davinci

![Image](https://github.com/user-attachments/assets/ee8a167b-7cae-44bb-b6cf-493953ae5c49)

My log
Platform: Windows 10
 Platform version: 10.0.26100
 OS: 10 10.0.26100 SP0 Multiprocessor Free  ('', '', '')  
 running Python 3.11.9.final.0
-------------- (__main__.py:32)
2025-02-25 11:30:29,320 - StAI - DEBUG: FFmpeg not found in current working directory: C:\Users\sonde\AppData\Local\Programs\StoryToolkitAI\ffmpeg.exe. (storytoolkitai.py:599)
2025-02-25 11:30:29,320 - StAI - DEBUG: Found FFmpeg in _internal directory. (storytoolkitai.py:605)
2025-02-25 11:30:29,321 - StAI - DEBUG: Checking ffmpeg binary: C:\Users\sonde\AppData\Local\Programs\StoryToolkitAI\_internal\ffmpeg.exe (storytoolkitai.py:629)
2025-02-25 11:30:29,343 - StAI - DEBUG: FFmpeg exit code: 1 (storytoolkitai.py:634)
2025-02-25 11:30:29,344 - StAI - DEBUG: FFmpeg found at C:\Users\sonde\AppData\Local\Programs\StoryToolkitAI\_internal\ffmpeg.exe (storytoolkitai.py:637)
2025-02-25 11:30:36,252 - StAI - DEBUG: Loading config file C:\Users\sonde\StoryToolkitAI\config.json. (storytoolkitai.py:368)
2025-02-25 11:30:36,253 - StAI - DEBUG: No API key found. (storytoolkitai.py:445)
2025-02-25 11:30:36,254 - StAI - DEBUG: Checking for latest standalone release. (storytoolkitai.py:460)
2025-02-25 11:30:36,254 - StAI - INFO: [1m[4mRunning StoryToolkitAI version 0.25.1.1 (standalone) (storytoolkitai.py:93)
2025-02-25 11:30:36,257 - StAI - DEBUG: Using cuda for Torch. (toolkit_ops.py:761)
2025-02-25 11:30:36,258 - StAI - DEBUG: MotsResolve module initialized. (mots_resolve.py:42)
2025-02-25 11:31:23,206 - StAI - DEBUG: 

my system windows 11 24H2
Python versions installed on machine: 3.11.9  64bit (trying 3.11.0(64bit), 3.11.0(32bit), 3.10. 3.13)
StoryToolkitAI Version 0.25.1  CUDA  (0.23 Working Great With Davinci)

![Image](https://github.com/user-attachments/assets/0d2faea3-6a36-4304-82d6-14f091be4d73)

![Image](https://github.com/user-attachments/assets/d86b395c-b177-49f2-b006-aca95d6cfe79)

**Comment by octimot** [comment]
@sonderling @iamfibi 

Could you try to reinstall Python 3.11.9, but this time make sure to check these features:

**Optional Features** - check everything, including `py launcher` and `for all users (requires admin privileges)`

**Advanced options** - make sure to check `Install Python 3.11 for all users`, `Add Python to environment variables` and `Precompile standard library`

@sonderling It looks like you might have another python installed in WindowsApps (although sometimes that's just a placeholder). Open _Add or Remove programs_ and look for anything python related and make sure to remove it.

Fingers crossed that this works... we're still trying to figure out if we can force Resolve to choose a specific python installation... but Blackmagic stays quiet...

**Comment by sonderling** [comment]
Thank you very much for your interest in helping us.
I did everything according to the instructions you wrote above. 
But nothing's changed.
I uninstall each time through the  manager and only then install a new one

![Image](https://github.com/user-attachments/assets/8e773e1a-2dec-4571-b905-43bdc8e75c64)


And yes, that's a very interesting fact.
when you type in the command
```
py -0
 -V:3.11 *        Python 3.11 (64-bit)
```
entering python itself gives a different version
```
C:\Users\sonde>python
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
Maybe that's the problem? Screen

![Image](https://github.com/user-attachments/assets/8f9323aa-b613-494f-bfe1-ef8ba650d43b)


P.S.
I tried installing the Python version from the marketplace :)
It got worse

![Image](https://github.com/user-attachments/assets/2ec4395a-03e7-4630-9937-81185c7f85c5)

but the same thing with version 3.11.7

![Image](https://github.com/user-attachments/assets/2ddd42e5-85a2-4c81-8c65-76541da0fa7e)

**Comment by octimot** [comment]
Just to make sure that we are in sync here, are you using the official Python installer with the options that I mentioned checked?

[https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe](https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe)

**Comment by sonderling** [comment]
Yes, I used installer from your link

![Image](https://github.com/user-attachments/assets/681a77a8-7a44-4bd7-9fe1-96698dfe53fe)


Maybe try uninstalling StoryToolkitAI completely?
Last time I uninstalled and reinstalled. It didn't download the Large model from the web. It was already on the computer.
Maybe some files were not deleted from the previous version when reinstalling?

**Comment by iamfibi** [comment]
I don't think removing the StoryToolKitAI will solve the problem, because I already tried it multiple times, even reinstalling my Windows (Completely clean XD) But you can try, perhaps it will work for you @sonderling

**Comment by sonderling** [comment]
If I understand correctly, Python does not pass the version check and then nothing happens.
Maybe remove version check in a line of code and see what happens?

**Comment by octimot** [comment]
I just realized that there might actually be a problem with the `py` version installed on your system. StoryToolkitAI is checking for the python versions relying on a very specific output from `py`, but this might have changed in the version you have on your machines.

Would you mind trying to start the tool with the `--skip-python-check` argument from the command prompt?

@iamfibi for the git version, just add `--skip-python-check` at the end of the start command

@sonderling for the standalone version:
1. Go to the folder where you installed StoryToolkitAI (probably `C:\Users\sonde\AppData\Local\Programs\StoryToolkitAI\`)
2. In the explorer top bar type in `cmd` to open up a Command Prompt in the installation folder
3. Then execute `StoryToolkitAI.0.25.1.WIN.CUDA.exe --debug --skip-python-check`

In both cases, make sure the tool tries to connect to Resolve: from the menu -> Integrations -> Connect to Resolve API.

**Comment by octimot** [comment]
I just pushed commit https://github.com/octimot/StoryToolkitAI/commit/cd57533af7dfb89246f29fb006385e4f4990cb61 that should cover the different `py` version formatting, but the `--skip-python-check` should do the trick too if you can't update (the update for the standalone needs to be compiled).

**Comment by octimot** [comment]
Yea!!! I think I found the issue and I'll patch it asap!

@iamfibi could you confirm if the new git push works on your side? thanks!

**Comment by iamfibi** [comment]
unfortunately, in my side the problem still persist even with --skip-python-check 

![Image](https://github.com/user-attachments/assets/2bb0ae6c-aa09-424a-9190-9ee7b9628ab5)

or am I wrong to start the tool?

here is the debug
Platform: Windows 10
 Platform version: 10.0.26100
 OS: 10 10.0.26100 SP0 Multiprocessor Free  ('', '', '')  
 running Python 3.11.9.final.0
-------------- (__main__.py:31)
2025-02-27 09:21:32,448 - StAI - DEBUG: Checking package requirements from C:\Users\DESIGN02\Desktop\Transcript\StoryToolkitAI\requirements.txt (__main__.py:65)
2025-02-27 09:21:32,816 - StAI - DEBUG: FFmpeg not found in current working directory: C:\Users\DESIGN02\Desktop\Transcript\StoryToolkitAI\ffmpeg.exe. (storytoolkitai.py:599)
2025-02-27 09:21:32,816 - StAI - DEBUG: FFmpeg not found in _internal directory: C:\Users\DESIGN02\Desktop\Transcript\StoryToolkitAI\_internal\ffmpeg.exe (storytoolkitai.py:609)
2025-02-27 09:21:32,816 - StAI - DEBUG: FFMPEG_BINARY env variable is empty. Looking for FFmpeg in PATH. (storytoolkitai.py:618)
2025-02-27 09:21:32,818 - StAI - DEBUG: Checking ffmpeg binary: C:\ProgramData\chocolatey\bin\ffmpeg.EXE (storytoolkitai.py:629)
2025-02-27 09:21:32,867 - StAI - DEBUG: FFmpeg exit code: 1 (storytoolkitai.py:634)
2025-02-27 09:21:32,867 - StAI - DEBUG: FFmpeg found at C:\ProgramData\chocolatey\bin\ffmpeg.EXE (storytoolkitai.py:637)
2025-02-27 09:21:39,413 - StAI - DEBUG: Loading config file C:\Users\DESIGN02\StoryToolkitAI\config.json. (storytoolkitai.py:368)
2025-02-27 09:21:39,414 - StAI - DEBUG: No API key found. (storytoolkitai.py:445)
2025-02-27 09:21:39,414 - StAI - DEBUG: Checking for latest version on api.storytoolkit.ai. (storytoolkitai.py:481)
2025-02-27 09:21:39,438 - StAI - INFO: [1m[4mRunning StoryToolkitAI version 0.25.1_bfd6009  (storytoolkitai.py:93)
2025-02-27 09:21:39,438 - StAI - DEBUG: Using cpu for Torch. (toolkit_ops.py:916)
2025-02-27 09:21:39,439 - StAI - DEBUG: Resolve API disabled via config. (toolkit_ops.py:342)
2025-02-27 09:21:39,439 - StAI - DEBUG: No items left in the queue. Try to ping the queue again later. (processing_queue.py:833)
2025-02-27 09:21:39,499 - StAI - DEBUG: Running with TK 8.6.12 (toolkit_ui.py:1436)
2025-02-27 09:21:40,035 - StAI - INFO: Starting StoryToolkitAI GUI (toolkit_ui.py:3179)
2025-02-27 09:21:40,501 - StAI - DEBUG: No update available. (toolkit_ui.py:1631)
2025-02-27 09:21:42,605 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2312)
2025-02-27 09:21:42,605 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-27 09:21:42,606 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2312)
2025-02-27 09:21:42,606 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-27 09:21:42,607 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2312)
2025-02-27 09:21:42,607 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-27 09:21:42,607 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2312)
2025-02-27 09:21:42,607 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-27 09:21:42,607 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2312)
2025-02-27 09:21:42,608 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-27 09:21:42,608 - StAI - DEBUG: Window type not found for window_id: None (toolkit_ui.py:2312)
2025-02-27 09:21:42,608 - StAI - DEBUG: No window id found. Not updating the menu bar. (menu.py:114)
2025-02-27 09:21:43,242 - StAI - DEBUG: MotsResolve module initialized. (mots_resolve.py:42)

**Comment by octimot** [comment]
@iamfibi 
> 2025-02-27 09:21:39,438 - StAI - INFO: �[1m�[4mRunning StoryToolkitAI version 0.25.1_bfd6009 (storytoolkitai.py:93)

It looks like you're still missing 2 commits. Could you do a `git pull` inside the installation folder to force an update?

Also, make sure to try to re-connect to the Resolve API, by going into Menu -> Integrations -> Connect to Resolve API. Right now the tool disabled the automatic re-connection to avoid errors:
> 2025-02-27 09:21:39,439 - StAI - DEBUG: Resolve API disabled via config. (toolkit_ops.py:342)

**Comment by iamfibi** [comment]
It works! Really thanks to you for helping!!!

![Image](https://github.com/user-attachments/assets/cb06c968-2982-4144-8e00-05a7a02caa32)

**Comment by octimot** [comment]
Cool! Thanks!

@sonderling I've just updated the links for the re-compiled standalone version too: https://www.patreon.com/posts/122690275

**Comment by sonderling** [comment]
Reinstalled the new version everything works Thank you very much!!!! You are awesome!!!!
And your program is just fire!!!
Huge kudos to you for the hard work you put into this project!!!

**Comment by octimot** [comment]
Great! I'm happy to hear that, thanks for the help on this!
