### ISSUE TITLE
Cannot save Setting Preferences due to Invalid API Token - API token was not Set / Modified

### ISSUE THREAD

**Issue by Mkhozi** [octimot/StoryToolkitAI#87]
Cause : API Token is initialized to 0 under Setting Preferences. Erasing the 0 value allows saving settings...  

        At first launch, config.json is initialized with "api_token": False  should be "api_token": ""
        False displays as 0 when converted to text under Setting Preferences

Fix :

In app.py under def check_api_token(self, api_token=None):

The following default_if_none=False should be default_if_none=None

        if api_token is None:
            self.api_token = self.get_app_setting(setting_name='api_token', default_if_none=False)   <--- here
        else:
            self.api_token = api_token

**Comment by octimot** [comment]
Fixed, thanks for the heads up @Mkhozi!

**Comment by t-hayash** [comment]
This issue is still present in the standalone version 18.0.1arm64
![Screen Shot 2023-04-12 at 1 31 50 PM](https://user-images.githubusercontent.com/128439073/231577945-e879fb9e-6e14-4eb8-9bbc-ec32278bb838.png)

**Comment by octimot** [comment]
Thanks for reporting this!

It seems to be a bug on the Preferences window, but we'll fix it on the next update.
